version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY='${SECRET}'
      - DEBUG='${DEBUG}'
      - DB_NAME='${DB_NAME}'
      - DB_USER='${DB_USER}'
      - DB_PASSWORD='${DB_PASSWORD}'
      - DB_HOST='db'
      - DB_PORT='5432'

  db:
    image: 'postgres:13'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB='${DB_NAME}'
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'

volumes:
  postgres_data: