# Generated by Django 4.2.15 on 2024-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_director_birth_date_director_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
